sudo: false  # enable caching
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabsnap
  - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
  - test -n "$STACK_ARGS" && cp -a $HOME/.ghc $HOME/.cabsnap/ghc || true

matrix:
  include:
  - env: CABALVER=1.24 GHCVER=8.0.2
    compiler: "ghc-8.0.2"
    addons: {apt: {packages: [ghc-8.0.2, cabal-install-1.24], sources: [hvr-ghc]}}

  - env: CABALVER=1.24 GHCVER=8.2.2
    compiler: "ghc-8.2.2"
    addons: {apt: {packages: [ghc-8.2.1, cabal-install-1.24], sources: [hvr-ghc]}}

  - env: CABALVER=1.24 GHCVER=8.4.1
    compiler: "ghc-8.4.1"
    addons: {apt: {packages: [ghc-8.4.1, cabal-install-1.24], sources: [hvr-ghc]}}

  allow_failures:
  - env: CABALVER=1.24 GHCVER=8.4.1

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

- export PATH=/opt/ghc/bin:/opt/cabal/$CABALVER/bin:$PATH
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin

install:
- |
  test -n "$CABALVER" || return 0
  cabal --version
  echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
  then
    zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz > \
         $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
  fi
  travis_retry cabal update -v
  sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
  cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
  sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt

  # check whether current requested install-plan matches cached package-db snapshot
  if diff -u $HOME/.cabsnap/installplan.txt installplan.txt;
  then
    echo "cabal build-cache HIT";
    rm -rfv .ghc;
    cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
    cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
    which c2hs || cabal install c2hs;
  else
    echo "cabal build-cache MISS";
    rm -rf $HOME/.cabsnap;
    mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
    cabal install --only-dependencies --enable-tests --enable-benchmarks;
    cabal install c2hs;
  fi

  # snapshot package-db on cache miss
  if [ ! -d $HOME/.cabsnap ];
  then
    echo "snapshotting package-db to build-cache";
    mkdir $HOME/.cabsnap;
    cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
    cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
  fi

script:
- if test -n "$CABALVER" -a -f configure.ac ; then autoreconf -i ; fi
- if test -n "$CABALVER" ; then cabal configure --enable-tests --enable-benchmarks -v2 ; fi  # -v2 provides useful information for debugging
- if test -n "$CABALVER" ; then cabal build ; fi   # this builds all libraries and executables (including tests/benchmarks)
- if test -n "$CABALVER" ; then cabal test ; fi
- if test -n "$CABALVER" ; then cabal haddock ; fi
- if test -n "$CABALVER" ; then cabal check ; fi
- if test -n "$CABALVER" ; then cabal sdist ; fi  # tests that a source-distribution can be generated
